// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDifbnJzTfvMNyzPcS9iQq7yeu7AhpDWIw',
    appId: '1:427895096068:web:299a40704209e488fe4651',
    messagingSenderId: '427895096068',
    projectId: 'localmate-88aad',
    authDomain: 'localmate-88aad.firebaseapp.com',
    storageBucket: 'localmate-88aad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2wDciIsJkODeYtjsHlZ1hf8bc34yWNE',
    appId: '1:427895096068:android:5451c93388b40fb9fe4651',
    messagingSenderId: '427895096068',
    projectId: 'localmate-88aad',
    storageBucket: 'localmate-88aad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbilUO8xML3IXYvpdZ6aDQBpen67-7368',
    appId: '1:427895096068:ios:4780be6615faa3fefe4651',
    messagingSenderId: '427895096068',
    projectId: 'localmate-88aad',
    storageBucket: 'localmate-88aad.firebasestorage.app',
    iosBundleId: 'com.hanajungjun.localmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbilUO8xML3IXYvpdZ6aDQBpen67-7368',
    appId: '1:427895096068:ios:52bd9f7e6543d3fafe4651',
    messagingSenderId: '427895096068',
    projectId: 'localmate-88aad',
    storageBucket: 'localmate-88aad.firebasestorage.app',
    iosBundleId: 'com.example.localMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDifbnJzTfvMNyzPcS9iQq7yeu7AhpDWIw',
    appId: '1:427895096068:web:4eafaae6ea4bd398fe4651',
    messagingSenderId: '427895096068',
    projectId: 'localmate-88aad',
    authDomain: 'localmate-88aad.firebaseapp.com',
    storageBucket: 'localmate-88aad.firebasestorage.app',
  );

}